### PR TITLE
chore(deps): upgrade dependencies and runtime to Node.js 20

### LINKED ISSUE #28: GitHub Actions asks for upgrade to Node.js 20
Node.js 16 actions are deprecated. See https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

When running this action, GitHub issues
"Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: varunsridharan/action-github-workflow-sync@3.3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/."

### PR DESCRIPTION
**Pull request by mgerlach**
also add .gitignore file for node modules, Intellij IDEA and VScode

fixes #28

### CODE REVIEW

**Comment by mgerlach** [comment]
@varunsridharan would this work? If so, could you release it?

**Review by smlgbl — APPROVED** [review]

**Comment by mgerlach** [comment]
@varunsridharan ping... any chance to get this released?

**Comment by mgerlach** [comment]
Pinging again...

**Comment by patrickc91** [comment]
Hoping this ping helps a little bit. Perhaps it's time to swap to a fork?

**Comment by mgerlach** [comment]
Hello @varunsridharan any intentions to do this?

**Comment by steveteuber** [comment]
Now the main branch is broken, see the error below:

```
/home/runner/work/_actions/varunsridharan/action-github-workflow-sync/main/node_modules/@octokit/plugin-throttling/dist-node/index.js:172
    throw new Error(`octokit/plugin-throttling error:
^
Error: octokit/plugin-throttling error:
        You must pass the onSecondaryRateLimit and onRateLimit error handlers.
        See https://octokit.github.io/rest.js/#throttling

        const octokit = new Octokit({
          throttle: {
            onSecondaryRateLimit: (retryAfter, options) => {/* ... */},
            onRateLimit: (retryAfter, options) => {/* ... */}
          }
        })
```

**Comment by varunsridharan** [comment]
Hello everyone,

Due to personal reasons and health issues, I am currently unable to work on my open-source projects. I truly appreciate all the support and contributions from this amazing community; your involvement has been invaluable in driving these projects forward.

If anyone is interested in collaborating or even taking over one of these projects, please reach out to me directly. I’d be happy to discuss adding someone who can continue building and supporting these tools. Thank you all again for your understanding and support during this time.

Best regards,
Varun Sridharan

E-Mail : varunsridharan23@gmail.com

@steveteuber @patrickc91 @mgerlach

**Comment by mgerlach** [comment]
@steveteuber @smlgbl @varunsridharan see #31

**Pull request merged**
